- type: department
  id: TraumaTeam
  name: department-Trauma
  description: department-Trauma-description
  color: "#00ab86"
  weight: -10
  roles:
  - TraumaMedTech
  - TraumaParamedic
  - TraumaRessurector
  - TraumaRepresentative

- type: department
  id: PhoenixInitiative
  name: department-Phoenix
  description: department-Phoenix-description
  color: "#ff4500"
  weight: -10
  roles:
  - PhoenixLeader
  - PhoenixBrigadier
  - PhoenixSecurityOfficer
  - PhoenixTechnician
